//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace animalsDataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAnimal
    {
        public int IdRegistroAnimal { get; set; }
        public int IdTipoAnimal { get; set; }
        public int IdEstadoAnimal { get; set; }
        public int IdSituacaoAnimal { get; set; }
        public string Descricao { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    
        public virtual EstadoAnimal EstadoAnimal { get; set; }
        public virtual SituacaoAnimal SituacaoAnimal { get; set; }
        public virtual TipoAnimal TipoAnimal { get; set; }
    }
}
